version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: farm-to-fork-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: farm-to-fork
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - farm-network

volumes:
  mongodb_data:

networks:
  farm-network:
    driver: bridge